2025-08-12 11:46:04,667 - pyclif.adt - INFO - Initialized adt table
2025-08-12 11:46:04,667 - pyclif.adt - INFO - Data directory: /Users/kavenchhikara/Desktop/CLIF/pyCLIF/src/clifpy/data/clif_demo
2025-08-12 11:46:04,667 - pyclif.adt - INFO - File type: parquet
2025-08-12 11:46:04,667 - pyclif.adt - INFO - Timezone: UTC
2025-08-12 11:46:04,667 - pyclif.adt - INFO - Output directory: /Users/kavenchhikara/Desktop/CLIF/pyCLIF/output
2025-08-12 11:46:04,669 - pyclif.adt - INFO - Loaded schema from /Users/kavenchhikara/Desktop/CLIF/pyCLIF/src/clifpy/schemas/adt_schema.yaml
2025-08-12 11:46:04,669 - pyclif.adt - INFO - Starting validation
2025-08-12 11:46:04,669 - pyclif.adt - INFO - Running schema validation
2025-08-12 11:46:04,670 - pyclif.adt - WARNING - Schema validation found 4 errors
2025-08-12 11:46:04,670 - pyclif.adt - INFO - Checking for duplicates on composite keys
2025-08-12 11:46:04,670 - pyclif.adt - INFO - Calculating missing data statistics
2025-08-12 11:46:04,671 - pyclif.adt - INFO - Saved missing data statistics to /Users/kavenchhikara/Desktop/CLIF/pyCLIF/output/missing_data_stats_adt.csv
2025-08-12 11:46:04,672 - pyclif.adt - INFO - Missing data: 32.19% (2925 cells)
2025-08-12 11:46:04,672 - pyclif.adt - INFO - Cohort sizes: {'patient_id': 100, 'patient_id_with_nulls': np.int64(0), 'hospitalization_id': 275, 'hospitalization_id_with_nulls': np.int64(0), 'total_rows': 1136}
2025-08-12 11:46:04,672 - pyclif.adt - WARNING - Validation completed with 4 error(s)
2025-08-12 11:46:04,673 - pyclif.adt - INFO - Saved validation errors to /Users/kavenchhikara/Desktop/CLIF/pyCLIF/output/validation_errors_adt.csv
